package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Class struct {
	CreatedAt  *time.Time `json:"created_at" bson:"created_at"`
	Id         string     `json:"id" bson:"_id,omitempty"`
	Key        string     `json:"key" bson:"key"`
	LinksIDs   []string   `json:"links_ids" bson:"links_ids"`
	Name       string     `json:"name" bson:"name"`
	ObjectsIDs []string   `json:"objects_ids" bson:"objects_ids"`
	OntologyID string     `json:"ontology_id" bson:"ontology_id"`
	TraitsIDs  []string   `json:"traits_ids" bson:"traits_ids"`
	UpdatedAt  *time.Time `json:"updated_at" bson:"updated_at"`
	UserID     string     `json:"user_id" bson:"user_id"`
}

func NewClass() *Class {
	return &Class{}
}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (class *Class) Kind() data.Kind {
	return ClassKind
}

// just returns itself for now
func (class *Class) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = class.ID()
	return foo
}

func (class *Class) SetID(id data.ID) {
	class.Id = id.String()
}

func (class *Class) ID() data.ID {
	return data.ID(class.Id)
}

func (class *Class) IncludeLink(link *Link) {
	class.LinksIDs = append(class.LinksIDs, link.ID().String())
}

func (class *Class) ExcludeLink(link *Link) {
	tmp := make([]string, 0)
	id := link.ID().String()
	for _, s := range class.LinksIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	class.LinksIDs = tmp
}

func (class *Class) LinksIter(store data.Store) (data.ModelIterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(class.LinksIDs), store), nil
}

func (class *Class) Links(store data.Store) ([]*Link, error) {

	links := make([]*Link, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(class.LinksIDs), store)
	link := NewLink()
	for iter.Next(link) {
		links = append(links, link)
		link = NewLink()
	}
	return links, nil
}

func (class *Class) IncludeObject(object *Object) {
	class.ObjectsIDs = append(class.ObjectsIDs, object.ID().String())
}

func (class *Class) ExcludeObject(object *Object) {
	tmp := make([]string, 0)
	id := object.ID().String()
	for _, s := range class.ObjectsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	class.ObjectsIDs = tmp
}

func (class *Class) ObjectsIter(store data.Store) (data.ModelIterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(class.ObjectsIDs), store), nil
}

func (class *Class) Objects(store data.Store) ([]*Object, error) {

	objects := make([]*Object, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(class.ObjectsIDs), store)
	object := NewObject()
	for iter.Next(object) {
		objects = append(objects, object)
		object = NewObject()
	}
	return objects, nil
}

func (class *Class) SetOntology(ontology *Ontology) error {
	class.OntologyID = ontology.ID().String()
	return nil
}

func (class *Class) Ontology(store data.Store) (*Ontology, error) {
	if class.OntologyID == "" {
		return nil, ErrEmptyLink
	}

	ontology := NewOntology()
	pid, _ := mongo.ParseObjectID(class.OntologyID)
	ontology.SetID(data.ID(pid.Hex()))
	return ontology, store.PopulateByID(ontology)

}

func (class *Class) IncludeTrait(trait *Trait) {
	class.TraitsIDs = append(class.TraitsIDs, trait.ID().String())
}

func (class *Class) ExcludeTrait(trait *Trait) {
	tmp := make([]string, 0)
	id := trait.ID().String()
	for _, s := range class.TraitsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	class.TraitsIDs = tmp
}

func (class *Class) TraitsIter(store data.Store) (data.ModelIterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(class.TraitsIDs), store), nil
}

func (class *Class) Traits(store data.Store) ([]*Trait, error) {

	traits := make([]*Trait, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(class.TraitsIDs), store)
	trait := NewTrait()
	for iter.Next(trait) {
		traits = append(traits, trait)
		trait = NewTrait()
	}
	return traits, nil
}

func (class *Class) SetUser(user *User) error {
	class.UserID = user.ID().String()
	return nil
}

func (class *Class) User(store data.Store) (*User, error) {
	if class.UserID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(class.UserID)
	user.SetID(data.ID(pid.Hex()))
	return user, store.PopulateByID(user)

}

func (class *Class) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt *time.Time `json:"created_at" bson:"created_at"`

		Id string `json:"id" bson:"_id,omitempty"`

		Key string `json:"key" bson:"key"`

		Name string `json:"name" bson:"name"`

		UpdatedAt *time.Time `json:"updated_at" bson:"updated_at"`

		LinksIDs []string `json:"links_ids" bson:"links_ids"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OntologyID string `json:"ontology_id" bson:"ontology_id"`

		TraitsIDs []string `json:"traits_ids" bson:"traits_ids"`

		UserID string `json:"user_id" bson:"user_id"`
	}{

		CreatedAt: class.CreatedAt,

		Key: class.Key,

		Name: class.Name,

		UpdatedAt: class.UpdatedAt,

		LinksIDs: class.LinksIDs,

		ObjectsIDs: class.ObjectsIDs,

		OntologyID: class.OntologyID,

		TraitsIDs: class.TraitsIDs,

		UserID: class.UserID,
	}, nil

}

func (class *Class) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt *time.Time `json:"created_at" bson:"created_at"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Key string `json:"key" bson:"key"`

		Name string `json:"name" bson:"name"`

		UpdatedAt *time.Time `json:"updated_at" bson:"updated_at"`

		LinksIDs []string `json:"links_ids" bson:"links_ids"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OntologyID string `json:"ontology_id" bson:"ontology_id"`

		TraitsIDs []string `json:"traits_ids" bson:"traits_ids"`

		UserID string `json:"user_id" bson:"user_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	class.CreatedAt = tmp.CreatedAt

	class.Id = tmp.Id.Hex()

	class.Key = tmp.Key

	class.Name = tmp.Name

	class.UpdatedAt = tmp.UpdatedAt

	class.LinksIDs = tmp.LinksIDs

	class.ObjectsIDs = tmp.ObjectsIDs

	class.OntologyID = tmp.OntologyID

	class.TraitsIDs = tmp.TraitsIDs

	class.UserID = tmp.UserID

	return nil

}
