package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Context struct {
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`
	Domain    string    `json:"domain" bson:"domain"`
	Id        string    `json:"id" bson:"_id,omitempty"`
	Ids       []string  `json:"ids" bson:"ids"`
	OwnerID   string    `json:"owner_id" bson:"owner_id"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

func NewContext() *Context {
	return &Context{}
}

func FindContext(db data.DB, id data.ID) (*Context, error) {

	context := NewContext()
	context.SetID(id)

	return context, db.PopulateByID(context)

}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (context *Context) Kind() data.Kind {
	return ContextKind
}

// just returns itself for now
func (context *Context) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = context.ID()
	return foo
}

func (context *Context) SetID(id data.ID) {
	context.Id = id.String()
}

func (context *Context) ID() data.ID {
	return data.ID(context.Id)
}

func (context *Context) SetOwner(user *User) error {
	context.OwnerID = user.ID().String()
	return nil
}

func (context *Context) Owner(db data.DB) (*User, error) {
	if context.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(context.OwnerID)
	user.SetID(data.ID(pid.Hex()))
	return user, db.PopulateByID(user)

}

func (context *Context) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := context.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := context.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(context); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

// BSON {{{
func (context *Context) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Domain string `json:"domain" bson:"domain"`

		Id string `json:"id" bson:"_id,omitempty"`

		Ids []string `json:"ids" bson:"ids"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{

		CreatedAt: context.CreatedAt,

		DeletedAt: context.DeletedAt,

		Domain: context.Domain,

		Ids: context.Ids,

		UpdatedAt: context.UpdatedAt,

		OwnerID: context.OwnerID,
	}, nil

}

func (context *Context) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Domain string `json:"domain" bson:"domain"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Ids []string `json:"ids" bson:"ids"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	context.CreatedAt = tmp.CreatedAt

	context.DeletedAt = tmp.DeletedAt

	context.Domain = tmp.Domain

	context.Id = tmp.Id.Hex()

	context.Ids = tmp.Ids

	context.UpdatedAt = tmp.UpdatedAt

	context.OwnerID = tmp.OwnerID

	return nil

}

// BSON }}}
