package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Event struct {
	CreatedAt *time.Time `json:"created_at" bson:"created_at"`
	EndTime   *time.Time `json:"end_time" bson:"end_time"`
	Id        string     `json:"id" bson:"_id,omitempty"`
	Name      string     `json:"name" bson:"name"`
	StartTime *time.Time `json:"start_time" bson:"start_time"`
	UpdatedAt *time.Time `json:"updated_at" bson:"updated_at"`
	UserID    string     `json:"user_id" bson:"user_id"`
}

func NewEvent() *Event {
	return &Event{}
}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (event *Event) Kind() data.Kind {
	return EventKind
}

// just returns itself for now
func (event *Event) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = event.ID()
	return foo
}

func (event *Event) SetID(id data.ID) {
	event.Id = id.String()
}

func (event *Event) ID() data.ID {
	return data.ID(event.Id)
}

func (event *Event) SetUser(user *User) error {
	event.UserID = user.ID().String()
	return nil
}

func (event *Event) User(store data.Store) (*User, error) {
	if event.UserID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(event.UserID)
	user.SetID(data.ID(pid.Hex()))
	return user, store.PopulateByID(user)

}

func (event *Event) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt *time.Time `json:"created_at" bson:"created_at"`

		EndTime *time.Time `json:"end_time" bson:"end_time"`

		Id string `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		StartTime *time.Time `json:"start_time" bson:"start_time"`

		UpdatedAt *time.Time `json:"updated_at" bson:"updated_at"`

		UserID string `json:"user_id" bson:"user_id"`
	}{

		CreatedAt: event.CreatedAt,

		EndTime: event.EndTime,

		Name: event.Name,

		StartTime: event.StartTime,

		UpdatedAt: event.UpdatedAt,

		UserID: event.UserID,
	}, nil

}

func (event *Event) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt *time.Time `json:"created_at" bson:"created_at"`

		EndTime *time.Time `json:"end_time" bson:"end_time"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		StartTime *time.Time `json:"start_time" bson:"start_time"`

		UpdatedAt *time.Time `json:"updated_at" bson:"updated_at"`

		UserID string `json:"user_id" bson:"user_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	event.CreatedAt = tmp.CreatedAt

	event.EndTime = tmp.EndTime

	event.Id = tmp.Id.Hex()

	event.Name = tmp.Name

	event.StartTime = tmp.StartTime

	event.UpdatedAt = tmp.UpdatedAt

	event.UserID = tmp.UserID

	return nil

}
