package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Group struct {
	Access    string    `json:"access" bson:"access"`
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	Domain    string    `json:"domain" bson:"domain"`
	Id        string    `json:"id" bson:"_id,omitempty"`
	Ids       []string  `json:"ids" bson:"ids"`
	Name      string    `json:"name" bson:"name"`
	OwnerID   string    `json:"owner_id" bson:"owner_id"`
	UsersIDs  []string  `json:"users_ids" bson:"users_ids"`
}

func NewGroup() *Group {
	return &Group{}
}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (group *Group) Kind() data.Kind {
	return GroupKind
}

// just returns itself for now
func (group *Group) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = group.ID()
	return foo
}

func (group *Group) SetID(id data.ID) {
	group.Id = id.String()
}

func (group *Group) ID() data.ID {
	return data.ID(group.Id)
}

func (group *Group) SetOwner(user *User) error {
	group.OwnerID = user.ID().String()
	return nil
}

func (group *Group) Owner(db data.DB) (*User, error) {
	if group.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(group.OwnerID)
	user.SetID(data.ID(pid.Hex()))
	return user, db.PopulateByID(user)

}

func (group *Group) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := group.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := group.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(group); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

func (group *Group) IncludeUser(user *User) {
	group.UsersIDs = append(group.UsersIDs, user.ID().String())
}

func (group *Group) ExcludeUser(user *User) {
	tmp := make([]string, 0)
	id := user.ID().String()
	for _, s := range group.UsersIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	group.UsersIDs = tmp
}

func (group *Group) UsersIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(group.UsersIDs), db), nil
}

func (group *Group) Users(db data.DB) ([]*User, error) {

	users := make([]*User, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(group.UsersIDs), db)
	user := NewUser()
	for iter.Next(user) {
		users = append(users, user)
		user = NewUser()
	}
	return users, nil
}

// BSON {{{
func (group *Group) GetBSON() (interface{}, error) {

	return struct {
		Access string `json:"access" bson:"access"`

		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		Domain string `json:"domain" bson:"domain"`

		Id string `json:"id" bson:"_id,omitempty"`

		Ids []string `json:"ids" bson:"ids"`

		Name string `json:"name" bson:"name"`

		OwnerID string `json:"owner_id" bson:"owner_id"`

		UsersIDs []string `json:"users_ids" bson:"users_ids"`
	}{

		Access: group.Access,

		CreatedAt: group.CreatedAt,

		Domain: group.Domain,

		Ids: group.Ids,

		Name: group.Name,

		OwnerID: group.OwnerID,

		UsersIDs: group.UsersIDs,
	}, nil

}

func (group *Group) SetBSON(raw bson.Raw) error {

	tmp := struct {
		Access string `json:"access" bson:"access"`

		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		Domain string `json:"domain" bson:"domain"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Ids []string `json:"ids" bson:"ids"`

		Name string `json:"name" bson:"name"`

		OwnerID string `json:"owner_id" bson:"owner_id"`

		UsersIDs []string `json:"users_ids" bson:"users_ids"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	group.Access = tmp.Access

	group.CreatedAt = tmp.CreatedAt

	group.Domain = tmp.Domain

	group.Id = tmp.Id.Hex()

	group.Ids = tmp.Ids

	group.Name = tmp.Name

	group.OwnerID = tmp.OwnerID

	group.UsersIDs = tmp.UsersIDs

	return nil

}

// BSON }}}
