package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Model struct {
	CreatedAt    time.Time `json:"created_at" bson:"created_at"`
	DeletedAt    time.Time `json:"deleted_at" bson:"deleted_at"`
	Id           string    `json:"id" bson:"_id,omitempty"`
	Name         string    `json:"name" bson:"name"`
	ObjectsIDs   []string  `json:"objects_ids" bson:"objects_ids"`
	OntologyID   string    `json:"ontology_id" bson:"ontology_id"`
	OwnerID      string    `json:"owner_id" bson:"owner_id"`
	RelationsIDs []string  `json:"relations_ids" bson:"relations_ids"`
	TraitsIDs    []string  `json:"traits_ids" bson:"traits_ids"`
	UpdatedAt    time.Time `json:"updated_at" bson:"updated_at"`
}

func NewModel() *Model {
	return &Model{}
}

func FindModel(db data.DB, id data.ID) (*Model, error) {

	model := NewModel()
	model.SetID(id)

	return model, db.PopulateByID(model)

}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (model *Model) Kind() data.Kind {
	return ModelKind
}

// just returns itself for now
func (model *Model) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = model.ID()
	return foo
}

func (model *Model) SetID(id data.ID) {
	model.Id = id.String()
}

func (model *Model) ID() data.ID {
	return data.ID(model.Id)
}

func (model *Model) IncludeObject(object *Object) {
	model.ObjectsIDs = append(model.ObjectsIDs, object.ID().String())
}

func (model *Model) ExcludeObject(object *Object) {
	tmp := make([]string, 0)
	id := object.ID().String()
	for _, s := range model.ObjectsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	model.ObjectsIDs = tmp
}

func (model *Model) ObjectsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(model.ObjectsIDs), db), nil
}

func (model *Model) Objects(db data.DB) ([]*Object, error) {

	objects := make([]*Object, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(model.ObjectsIDs), db)
	object := NewObject()
	for iter.Next(object) {
		objects = append(objects, object)
		object = NewObject()
	}
	return objects, nil
}

func (model *Model) SetOntology(ontology *Ontology) error {
	model.OntologyID = ontology.ID().String()
	return nil
}

func (model *Model) Ontology(db data.DB) (*Ontology, error) {
	if model.OntologyID == "" {
		return nil, ErrEmptyLink
	}

	ontology := NewOntology()
	pid, _ := mongo.ParseObjectID(model.OntologyID)
	ontology.SetID(data.ID(pid.Hex()))
	return ontology, db.PopulateByID(ontology)

}

func (model *Model) OntologyOrCreate(db data.DB) (*Ontology, error) {
	ontology, err := model.Ontology(db)

	if err == ErrEmptyLink {
		ontology := NewOntology()
		ontology.SetID(db.NewID())
		if err := model.SetOntology(ontology); err != nil {
			return nil, err
		}

		if err := db.Save(ontology); err != nil {
			return nil, err
		}

		if err := db.Save(model); err != nil {
			return nil, err
		}

		return ontology, nil
	} else {
		return ontology, err
	}
}

func (model *Model) SetOwner(user *User) error {
	model.OwnerID = user.ID().String()
	return nil
}

func (model *Model) Owner(db data.DB) (*User, error) {
	if model.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(model.OwnerID)
	user.SetID(data.ID(pid.Hex()))
	return user, db.PopulateByID(user)

}

func (model *Model) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := model.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := model.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(model); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

func (model *Model) IncludeRelation(relation *Relation) {
	model.RelationsIDs = append(model.RelationsIDs, relation.ID().String())
}

func (model *Model) ExcludeRelation(relation *Relation) {
	tmp := make([]string, 0)
	id := relation.ID().String()
	for _, s := range model.RelationsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	model.RelationsIDs = tmp
}

func (model *Model) RelationsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(model.RelationsIDs), db), nil
}

func (model *Model) Relations(db data.DB) ([]*Relation, error) {

	relations := make([]*Relation, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(model.RelationsIDs), db)
	relation := NewRelation()
	for iter.Next(relation) {
		relations = append(relations, relation)
		relation = NewRelation()
	}
	return relations, nil
}

func (model *Model) IncludeTrait(trait *Trait) {
	model.TraitsIDs = append(model.TraitsIDs, trait.ID().String())
}

func (model *Model) ExcludeTrait(trait *Trait) {
	tmp := make([]string, 0)
	id := trait.ID().String()
	for _, s := range model.TraitsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	model.TraitsIDs = tmp
}

func (model *Model) TraitsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(model.TraitsIDs), db), nil
}

func (model *Model) Traits(db data.DB) ([]*Trait, error) {

	traits := make([]*Trait, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(model.TraitsIDs), db)
	trait := NewTrait()
	for iter.Next(trait) {
		traits = append(traits, trait)
		trait = NewTrait()
	}
	return traits, nil
}

// BSON {{{
func (model *Model) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id string `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OntologyID string `json:"ontology_id" bson:"ontology_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`

		RelationsIDs []string `json:"relations_ids" bson:"relations_ids"`

		TraitsIDs []string `json:"traits_ids" bson:"traits_ids"`
	}{

		CreatedAt: model.CreatedAt,

		DeletedAt: model.DeletedAt,

		Name: model.Name,

		UpdatedAt: model.UpdatedAt,

		ObjectsIDs: model.ObjectsIDs,

		OntologyID: model.OntologyID,

		OwnerID: model.OwnerID,

		RelationsIDs: model.RelationsIDs,

		TraitsIDs: model.TraitsIDs,
	}, nil

}

func (model *Model) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OntologyID string `json:"ontology_id" bson:"ontology_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`

		RelationsIDs []string `json:"relations_ids" bson:"relations_ids"`

		TraitsIDs []string `json:"traits_ids" bson:"traits_ids"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	model.CreatedAt = tmp.CreatedAt

	model.DeletedAt = tmp.DeletedAt

	model.Id = tmp.Id.Hex()

	model.Name = tmp.Name

	model.UpdatedAt = tmp.UpdatedAt

	model.ObjectsIDs = tmp.ObjectsIDs

	model.OntologyID = tmp.OntologyID

	model.OwnerID = tmp.OwnerID

	model.RelationsIDs = tmp.RelationsIDs

	model.TraitsIDs = tmp.TraitsIDs

	return nil

}

// BSON }}}
