package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Ontology struct {
	CreatedAt  time.Time `json:"created_at" bson:"created_at"`
	DeletedAt  time.Time `json:"deleted_at" bson:"deleted_at"`
	Id         string    `json:"id" bson:"_id,omitempty"`
	ModelsIDs  []string  `json:"models_ids" bson:"models_ids"`
	ObjectsIDs []string  `json:"objects_ids" bson:"objects_ids"`
	OwnerID    string    `json:"owner_id" bson:"owner_id"`
	UpdatedAt  time.Time `json:"updated_at" bson:"updated_at"`
}

func NewOntology() *Ontology {
	return &Ontology{}
}

func FindOntology(db data.DB, id data.ID) (*Ontology, error) {

	ontology := NewOntology()
	ontology.SetID(id)

	return ontology, db.PopulateByID(ontology)

}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (ontology *Ontology) Kind() data.Kind {
	return OntologyKind
}

// just returns itself for now
func (ontology *Ontology) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = ontology.ID()
	return foo
}

func (ontology *Ontology) SetID(id data.ID) {
	ontology.Id = id.String()
}

func (ontology *Ontology) ID() data.ID {
	return data.ID(ontology.Id)
}

func (ontology *Ontology) IncludeModel(model *Model) {
	ontology.ModelsIDs = append(ontology.ModelsIDs, model.ID().String())
}

func (ontology *Ontology) ExcludeModel(model *Model) {
	tmp := make([]string, 0)
	id := model.ID().String()
	for _, s := range ontology.ModelsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	ontology.ModelsIDs = tmp
}

func (ontology *Ontology) ModelsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(ontology.ModelsIDs), db), nil
}

func (ontology *Ontology) Models(db data.DB) ([]*Model, error) {

	models := make([]*Model, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(ontology.ModelsIDs), db)
	model := NewModel()
	for iter.Next(model) {
		models = append(models, model)
		model = NewModel()
	}
	return models, nil
}

func (ontology *Ontology) IncludeObject(object *Object) {
	ontology.ObjectsIDs = append(ontology.ObjectsIDs, object.ID().String())
}

func (ontology *Ontology) ExcludeObject(object *Object) {
	tmp := make([]string, 0)
	id := object.ID().String()
	for _, s := range ontology.ObjectsIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	ontology.ObjectsIDs = tmp
}

func (ontology *Ontology) ObjectsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(ontology.ObjectsIDs), db), nil
}

func (ontology *Ontology) Objects(db data.DB) ([]*Object, error) {

	objects := make([]*Object, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(ontology.ObjectsIDs), db)
	object := NewObject()
	for iter.Next(object) {
		objects = append(objects, object)
		object = NewObject()
	}
	return objects, nil
}

func (ontology *Ontology) SetOwner(user *User) error {
	ontology.OwnerID = user.ID().String()
	return nil
}

func (ontology *Ontology) Owner(db data.DB) (*User, error) {
	if ontology.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(ontology.OwnerID)
	user.SetID(data.ID(pid.Hex()))
	return user, db.PopulateByID(user)

}

func (ontology *Ontology) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := ontology.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := ontology.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(ontology); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

// BSON {{{
func (ontology *Ontology) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id string `json:"id" bson:"_id,omitempty"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		ModelsIDs []string `json:"models_ids" bson:"models_ids"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{

		CreatedAt: ontology.CreatedAt,

		DeletedAt: ontology.DeletedAt,

		UpdatedAt: ontology.UpdatedAt,

		ModelsIDs: ontology.ModelsIDs,

		ObjectsIDs: ontology.ObjectsIDs,

		OwnerID: ontology.OwnerID,
	}, nil

}

func (ontology *Ontology) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		ModelsIDs []string `json:"models_ids" bson:"models_ids"`

		ObjectsIDs []string `json:"objects_ids" bson:"objects_ids"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	ontology.CreatedAt = tmp.CreatedAt

	ontology.DeletedAt = tmp.DeletedAt

	ontology.Id = tmp.Id.Hex()

	ontology.UpdatedAt = tmp.UpdatedAt

	ontology.ModelsIDs = tmp.ModelsIDs

	ontology.ObjectsIDs = tmp.ObjectsIDs

	ontology.OwnerID = tmp.OwnerID

	return nil

}

// BSON }}}
