package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Session struct {
	CreatedAt    time.Time `json:"created_at" bson:"created_at"`
	CredentialID string    `json:"credential_id" bson:"credential_id"`
	ExpiresAfter int       `json:"expires_after" bson:"expires_after"`
	Id           string    `json:"id" bson:"_id,omitempty"`
	OwnerID      string    `json:"owner_id" bson:"owner_id"`
	Token        string    `json:"token" bson:"token"`
	UpdatedAt    time.Time `json:"updated_at" bson:"updated_at"`
}

func NewSession() *Session {
	return &Session{}
}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (session *Session) Kind() data.Kind {
	return SessionKind
}

// just returns itself for now
func (session *Session) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = session.ID()
	return foo
}

func (session *Session) SetID(id data.ID) {
	session.Id = id.String()
}

func (session *Session) ID() data.ID {
	return data.ID(session.Id)
}

func (session *Session) SetCredential(credential *Credential) error {
	session.CredentialID = credential.ID().String()
	return nil
}

func (session *Session) Credential(db data.DB) (*Credential, error) {
	if session.CredentialID == "" {
		return nil, ErrEmptyLink
	}

	credential := NewCredential()
	pid, _ := mongo.ParseObjectID(session.CredentialID)
	credential.SetID(data.ID(pid.Hex()))
	return credential, db.PopulateByID(credential)

}

func (session *Session) CredentialOrCreate(db data.DB) (*Credential, error) {
	credential, err := session.Credential(db)

	if err == ErrEmptyLink {
		credential := NewCredential()
		credential.SetID(db.NewID())
		if err := session.SetCredential(credential); err != nil {
			return nil, err
		}

		if err := db.Save(credential); err != nil {
			return nil, err
		}

		if err := db.Save(session); err != nil {
			return nil, err
		}

		return credential, nil
	} else {
		return credential, err
	}
}

func (session *Session) SetOwner(user *User) error {
	session.OwnerID = user.ID().String()
	return nil
}

func (session *Session) Owner(db data.DB) (*User, error) {
	if session.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	user := NewUser()
	pid, _ := mongo.ParseObjectID(session.OwnerID)
	user.SetID(data.ID(pid.Hex()))
	return user, db.PopulateByID(user)

}

func (session *Session) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := session.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := session.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(session); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

// BSON {{{
func (session *Session) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		ExpiresAfter int `json:"expires_after" bson:"expires_after"`

		Id string `json:"id" bson:"_id,omitempty"`

		Token string `json:"token" bson:"token"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		CredentialID string `json:"credential_id" bson:"credential_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{

		CreatedAt: session.CreatedAt,

		ExpiresAfter: session.ExpiresAfter,

		Token: session.Token,

		UpdatedAt: session.UpdatedAt,

		CredentialID: session.CredentialID,

		OwnerID: session.OwnerID,
	}, nil

}

func (session *Session) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		ExpiresAfter int `json:"expires_after" bson:"expires_after"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Token string `json:"token" bson:"token"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		CredentialID string `json:"credential_id" bson:"credential_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	session.CreatedAt = tmp.CreatedAt

	session.ExpiresAfter = tmp.ExpiresAfter

	session.Id = tmp.Id.Hex()

	session.Token = tmp.Token

	session.UpdatedAt = tmp.UpdatedAt

	session.CredentialID = tmp.CredentialID

	session.OwnerID = tmp.OwnerID

	return nil

}

// BSON }}}
