package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"github.com/elos/metis"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Tag struct {
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`
	EventsIds []string  `json:"events_ids" bson:"events_ids"`
	Id        string    `json:"id" bson:"_id,omitempty"`
	Name      string    `json:"name" bson:"name"`
	OwnerId   string    `json:"owner_id" bson:"owner_id"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

func NewTag() *Tag {
	return &Tag{}
}

func FindTag(db data.DB, id data.ID) (*Tag, error) {

	tag := NewTag()
	tag.SetID(id)

	return tag, db.PopulateByID(tag)

}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (tag *Tag) Kind() data.Kind {
	return TagKind
}

// just returns itself for now
func (tag *Tag) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = tag.ID()
	return foo
}

func (tag *Tag) SetID(id data.ID) {
	tag.Id = id.String()
}

func (tag *Tag) ID() data.ID {
	return data.ID(tag.Id)
}

func (tag *Tag) IncludeEvent(event *Event) {
	tag.EventsIds = append(tag.EventsIds, event.ID().String())
}

func (tag *Tag) ExcludeEvent(event *Event) {
	tmp := make([]string, 0)
	id := event.ID().String()
	for _, s := range tag.EventsIds {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	tag.EventsIds = tmp
}

func (tag *Tag) EventsIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(tag.EventsIds), db), nil
}

func (tag *Tag) Events(db data.DB) ([]*Event, error) {

	events := make([]*Event, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(tag.EventsIds), db)
	event := NewEvent()
	for iter.Next(event) {
		events = append(events, event)
		event = NewEvent()
	}
	return events, nil
}

func (tag *Tag) SetOwner(userArgument *User) error {
	tag.OwnerId = userArgument.ID().String()
	return nil
}

func (tag *Tag) Owner(db data.DB) (*User, error) {
	if tag.OwnerId == "" {
		return nil, ErrEmptyLink
	}

	userArgument := NewUser()
	pid, _ := mongo.ParseObjectID(tag.OwnerId)
	userArgument.SetID(data.ID(pid.Hex()))
	return userArgument, db.PopulateByID(userArgument)

}

func (tag *Tag) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := tag.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := tag.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(tag); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

// BSON {{{
func (tag *Tag) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id string `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		EventsIds []string `json:"events_ids" bson:"events_ids"`

		OwnerId string `json:"owner_id" bson:"owner_id"`
	}{

		CreatedAt: tag.CreatedAt,

		DeletedAt: tag.DeletedAt,

		Name: tag.Name,

		UpdatedAt: tag.UpdatedAt,

		EventsIds: tag.EventsIds,

		OwnerId: tag.OwnerId,
	}, nil

}

func (tag *Tag) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		EventsIds []string `json:"events_ids" bson:"events_ids"`

		OwnerId string `json:"owner_id" bson:"owner_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	tag.CreatedAt = tmp.CreatedAt

	tag.DeletedAt = tmp.DeletedAt

	tag.Id = tmp.Id.Hex()

	tag.Name = tmp.Name

	tag.UpdatedAt = tmp.UpdatedAt

	tag.EventsIds = tmp.EventsIds

	tag.OwnerId = tmp.OwnerId

	return nil

}

// BSON }}}

func (tag *Tag) FromStructure(structure map[string]interface{}) {

	if val, ok := structure["id"]; ok {
		tag.Id = val.(string)
	}

	if val, ok := structure["created_at"]; ok {
		tag.CreatedAt = val.(time.Time)
	}

	if val, ok := structure["updated_at"]; ok {
		tag.UpdatedAt = val.(time.Time)
	}

	if val, ok := structure["deleted_at"]; ok {
		tag.DeletedAt = val.(time.Time)
	}

	if val, ok := structure["name"]; ok {
		tag.Name = val.(string)
	}

	if val, ok := structure["events_ids"]; ok {
		tag.EventsIds = val.([]string)
	}

	if val, ok := structure["owner_id"]; ok {
		tag.OwnerId = val.(string)
	}

}

var TagStructure = map[string]metis.Primitive{

	"updated_at": 4,

	"deleted_at": 4,

	"name": 3,

	"id": 9,

	"created_at": 4,

	"owner_id": 9,

	"events_ids": 10,
}
