package models

import (
	"time"

	"github.com/elos/data"
	"github.com/elos/data/builtin/mongo"
	"gopkg.in/mgo.v2/bson"
)

// THIS FILE GENERATED BY METIS

// this type def generated by metis
type Trait struct {
	AttributesIDs []string  `json:"attributes_ids" bson:"attributes_ids"`
	CreatedAt     time.Time `json:"created_at" bson:"created_at"`
	DeletedAt     time.Time `json:"deleted_at" bson:"deleted_at"`
	Id            string    `json:"id" bson:"_id,omitempty"`
	ModelID       string    `json:"model_id" bson:"model_id"`
	Name          string    `json:"name" bson:"name"`
	OwnerID       string    `json:"owner_id" bson:"owner_id"`
	Primitive     string    `json:"primitive" bson:"primitive"`
	UpdatedAt     time.Time `json:"updated_at" bson:"updated_at"`
}

func NewTrait() *Trait {
	return &Trait{}
}

func FindTrait(db data.DB, id data.ID) (*Trait, error) {

	trait := NewTrait()
	trait.SetID(id)

	return trait, db.PopulateByID(trait)

}

// Kind is derived from the models package and is
// defined in type.go, shared among implementations
func (trait *Trait) Kind() data.Kind {
	return TraitKind
}

// just returns itself for now
func (trait *Trait) Concerned() []data.ID {
	foo := make([]data.ID, 1)
	foo[0] = trait.ID()
	return foo
}

func (trait *Trait) SetID(id data.ID) {
	trait.Id = id.String()
}

func (trait *Trait) ID() data.ID {
	return data.ID(trait.Id)
}

func (trait *Trait) IncludeAttribute(attribute *Attribute) {
	trait.AttributesIDs = append(trait.AttributesIDs, attribute.ID().String())
}

func (trait *Trait) ExcludeAttribute(attribute *Attribute) {
	tmp := make([]string, 0)
	id := attribute.ID().String()
	for _, s := range trait.AttributesIDs {
		if s != id {
			tmp = append(tmp, s)
		}
	}
	trait.AttributesIDs = tmp
}

func (trait *Trait) AttributesIter(db data.DB) (data.Iterator, error) {
	// not yet completely general
	return mongo.NewIDIter(mongo.NewIDSetFromStrings(trait.AttributesIDs), db), nil
}

func (trait *Trait) Attributes(db data.DB) ([]*Attribute, error) {

	attributes := make([]*Attribute, 0)
	iter := mongo.NewIDIter(mongo.NewIDSetFromStrings(trait.AttributesIDs), db)
	attribute := NewAttribute()
	for iter.Next(attribute) {
		attributes = append(attributes, attribute)
		attribute = NewAttribute()
	}
	return attributes, nil
}

func (trait *Trait) SetModel(modelArgument *Model) error {
	trait.ModelID = modelArgument.ID().String()
	return nil
}

func (trait *Trait) Model(db data.DB) (*Model, error) {
	if trait.ModelID == "" {
		return nil, ErrEmptyLink
	}

	modelArgument := NewModel()
	pid, _ := mongo.ParseObjectID(trait.ModelID)
	modelArgument.SetID(data.ID(pid.Hex()))
	return modelArgument, db.PopulateByID(modelArgument)

}

func (trait *Trait) ModelOrCreate(db data.DB) (*Model, error) {
	model, err := trait.Model(db)

	if err == ErrEmptyLink {
		model := NewModel()
		model.SetID(db.NewID())
		if err := trait.SetModel(model); err != nil {
			return nil, err
		}

		if err := db.Save(model); err != nil {
			return nil, err
		}

		if err := db.Save(trait); err != nil {
			return nil, err
		}

		return model, nil
	} else {
		return model, err
	}
}

func (trait *Trait) SetOwner(userArgument *User) error {
	trait.OwnerID = userArgument.ID().String()
	return nil
}

func (trait *Trait) Owner(db data.DB) (*User, error) {
	if trait.OwnerID == "" {
		return nil, ErrEmptyLink
	}

	userArgument := NewUser()
	pid, _ := mongo.ParseObjectID(trait.OwnerID)
	userArgument.SetID(data.ID(pid.Hex()))
	return userArgument, db.PopulateByID(userArgument)

}

func (trait *Trait) OwnerOrCreate(db data.DB) (*User, error) {
	user, err := trait.Owner(db)

	if err == ErrEmptyLink {
		user := NewUser()
		user.SetID(db.NewID())
		if err := trait.SetOwner(user); err != nil {
			return nil, err
		}

		if err := db.Save(user); err != nil {
			return nil, err
		}

		if err := db.Save(trait); err != nil {
			return nil, err
		}

		return user, nil
	} else {
		return user, err
	}
}

// BSON {{{
func (trait *Trait) GetBSON() (interface{}, error) {

	return struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id string `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		Primitive string `json:"primitive" bson:"primitive"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		AttributesIDs []string `json:"attributes_ids" bson:"attributes_ids"`

		ModelID string `json:"model_id" bson:"model_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{

		CreatedAt: trait.CreatedAt,

		DeletedAt: trait.DeletedAt,

		Name: trait.Name,

		Primitive: trait.Primitive,

		UpdatedAt: trait.UpdatedAt,

		AttributesIDs: trait.AttributesIDs,

		ModelID: trait.ModelID,

		OwnerID: trait.OwnerID,
	}, nil

}

func (trait *Trait) SetBSON(raw bson.Raw) error {

	tmp := struct {
		CreatedAt time.Time `json:"created_at" bson:"created_at"`

		DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`

		Id bson.ObjectId `json:"id" bson:"_id,omitempty"`

		Name string `json:"name" bson:"name"`

		Primitive string `json:"primitive" bson:"primitive"`

		UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`

		AttributesIDs []string `json:"attributes_ids" bson:"attributes_ids"`

		ModelID string `json:"model_id" bson:"model_id"`

		OwnerID string `json:"owner_id" bson:"owner_id"`
	}{}

	err := raw.Unmarshal(&tmp)
	if err != nil {
		return err
	}

	trait.CreatedAt = tmp.CreatedAt

	trait.DeletedAt = tmp.DeletedAt

	trait.Id = tmp.Id.Hex()

	trait.Name = tmp.Name

	trait.Primitive = tmp.Primitive

	trait.UpdatedAt = tmp.UpdatedAt

	trait.AttributesIDs = tmp.AttributesIDs

	trait.ModelID = tmp.ModelID

	trait.OwnerID = tmp.OwnerID

	return nil

}

// BSON }}}
